// Generated by CoffeeScript 1.8.0
(function() {
  var ColorsWidget;

  ColorsWidget = (function() {
    var drow, drow_stats, init, l, max, mobile_width, position, r, set_width, to;
    l = 'passive';
    position = 0;
    r = '';
    max = 0;
    mobile_width = 769;
    init = function() {
      return $.ajax('colors.json').done(function(data) {
        var color, _i, _len, _ref;
        $('#colors').wrap('<div id="wrap"></div>');
        $('#colors').before('<div id="count"></div>');
        _ref = data["colors"];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          color = _ref[_i];
          drow({
            d: color
          }, '#template', '#colors', 'append');
        }
        set_width();
        $(window).on('resize', function() {
          return set_width();
        });
        max = data["colors"].length;
        drow_stats(position + 1);
        $('#count').on('click', 'a', function() {
          if ($(this).hasClass('left')) {
            position -= 1;
          }
          if ($(this).hasClass('right')) {
            position += 1;
          }
          to();
          return false;
        });
        $('#colors').on('swiperight', function() {
          if ($(document).width() < mobile_width) {
            position -= 1;
            return to();
          }
        });
        return $('#colors').on('swipeleft', function() {
          if ($(document).width() < mobile_width) {
            position += 1;
            return to();
          }
        });
      });
    };
    to = function(n) {
      if (position < 0) {
        position = 0;
      }
      if (position > max - 1) {
        position = max - 1;
      }
      if (position === 0) {
        l = 'passive';
      } else {
        l = '';
      }
      if (position === max - 1) {
        r = 'passive';
      } else {
        r = '';
      }
      $('#colors').animate({
        'margin-left': -1 * position * 100 + '%'
      }, 200);
      return drow_stats(position + 1);
    };
    set_width = function() {
      if ($(document).width() < mobile_width) {
        return $('#colors li').css('width', $(document).width());
      } else {
        return $('#colors li').css('width', '');
      }
    };
    drow_stats = function(n) {
      return drow({
        d: n,
        l: l,
        r: r,
        max: max
      }, '#template1', '#count', 'replace');
    };
    drow = function(data, from, to, v) {
      var template;
      template = $(from).html();
      Mustache.parse(template);
      switch (v) {
        case 'append':
          return $(to).append(Mustache.render(template, data));
        case 'replace':
          return $(to).html(Mustache.render(template, data));
      }
    };
    return init();
  })();

}).call(this);
